final List<String> skills = [
  "SQL",
  "C++",
  "JavaScript",
  "Ruby",
  "PHP",
  "Swift",
  "Kotlin",
  "Go",
  "Rust",
  "Scala",
  "Perl",
  "R",
  "MATLAB",
  "SAS",
  "Julia",
  "COBOL",
  "Fortran",
  "ABAP",
  "PL/SQL",
  "T-SQL",
  "PL/pgSQL",
  "Transact-SQL",
  "Haskell",
  "Clojure",
  "Erlang",
  "Elixir",
  "F#",
  "OCaml",
  "Scheme",
  "Prolog",
  "Lisp",
  "TypeScript",
  "NoSQL",
  "MongoDB",
  "Cassandra",
  "PostgreSQL",
  "MySQL",
  "Oracle DB",
  "SQLite",
  "AWS",
  "Microsoft Azure",
  "Google Cloud Platform",
  "IBM Cloud",
  "Alibaba Cloud",
  "Oracle Cloud",
  "DigitalOcean",
  "VMware Cloud",
  "Encryption",
  "Firewalls",
  "VPNs",
  "Penetration Testing",
  "Ethical Hacking",
  "Threat Intelligence",
  "SIEM",
  "IAM",
  "Phishing",
  "Malware",
  "DDoS attacks",
  "Vulnerability Assessment",
  "PenTesting",
  "Cyber Laws and Regulations (GDPR)",
  "HIPAA",
  "Network Security",
  "Application Security",
  "Cloud Security",
  "IoT Security",
  "Blockchain Security",
  "Statistics",
  "Data Mining",
  "Predictive Analytics",
  "Machine Learning Algorithms Linear Regression",
  "Logistic Regression",
  "Decision Trees",
  "Random Forests",
  "SVM",
  "Neural Networks",
  "Deep Learning",
  "TensorFlow",
  "PyTorch",
  "Keras",
  "Pandas",
  "NumPy",
  "Matplotlib",
  "Scikit-learn",
  "Data Visualization",
  "Big Data",
  "Hadoop",
  "Spark",
  "Tableau",
  "Power BI",
  "HTML",
  "CSS",
  "React",
  "Angular",
  "Vue.js",
  "Node.js",
  "Django",
  "Ruby on Rails",
  "Flask",
  "WordPress",
  "Joomla",
  "Drupal",
  "iOS",
  "Objective-C",
  "Android",
  "Java",
  "Cross-platform frameworks",
  "Flutter",
  "Xamarin",
  "Linux",
  "Windows Server",
  "Bash scripting",
  "PowerShell",
  "DevOps",
  "Docker",
  "Kubernetes",
  "CI/CD pipelines",
  "Apache",
  "Nginx",
  "HTTP",
  "DNS",
  "TCP/IP",
  "VPN",
  "Proxy Servers",
  "CDN",
  "APIs (REST",
  "GraphQL)",
  "Web Services (SOAP)",
  "IoT",
  "5G",
  "Edge Computing",
  "Agile",
  "Scrum",
  "Kanban",
  "Waterfall Model",
  "Pair Programming",
  "Code Reviews",
  "Unit Testing",
  "Integration Testing",
  "TDD",
  "BDD",
  "AI Algorithms",
  "NLP",
  "Computer Vision",
  "Robotics",
  "Expert Systems",
  "MLOps",
  "Ethics in AI",
  "Virtual Machines",
  "Containers",
  "Hypervisors",
  "AWS Services (EC2",
  "S3",
  "Lambda",
  "RDS",
  "VPC)",
  "Azure Services (VMs",
  "Blob Storage",
  "Functions",
  "SQL Database",
  "Virtual Networks)",
  "GCP Services (Compute Engine",
  "Google Storage",
  "Cloud Functions",
  "Cloud SQL",
  "PMBOK",
  "Agile Project Management",
  "Scrum Master",
  "Product Owner",
  "Kanban Board",
  "Gantt Charts",
  "Risk Management",
  "Stakeholder Management",
  "Quantum Computing",
  "AR",
  "VR",
  "MR",
  "Biometrics",
  "Genetic Algorithms",
  "Nanotechnology",
  "Space Technology",
  "Oracle Database",
  "Microsoft SQL Server",
  "Redis",
  "Elasticsearch",
  "MariaDB",
  "AWS (Amazon Web Services)",
  "Azure (Microsoft Cloud)",
  "GCP (Google Cloud Platform)",
  "Vultr",
  "Linode",
  "Cisco Networking Devices",
  "Juniper Networks",
  "Fortinet Firewalls",
  "Palo Alto Networks",
  "Check Point Firewall-1",
  "F5 Load Balancers",
  "Arista Networks",
  "Cumulus Linux",
  "Yolo",
  "SIEM (Security Information and Event Management) tools like Splunk",
  "IBM QRadar",
  "Dart",
  "IDS/IPS (Intrusion Detection System / Intrusion Prevention System)",
  "VPN Solutions",
  "OpenVPN",
  "Cisco ASA",
  "Penetration Testing Tools (Metasploit",
  "Nmap",
  "Security Frameworks (ISO 27001",
  "NIST Cybersecurity Framework)",
  "Version Control Systems",
  "Git",
  "SVN",
  "Integrated Development Environments (IDEs) like Visual Studio",
  "IntelliJ IDEA",
  "Eclipse",
  "GitHub",
  "GitLab",
  "Bitbucket",
  "Build Automation Tools (Jenkins)",
  "Travis CI",
  "CircleCI",
  "Containerization and Orchestration Docker",
  "Kubernetes",
  "Xamarin (for cross-platform development)",
  "React Native",
  "Ionic Framework",
  "Apache HTTP Server",
  "IIS (Internet Information Services)",
  "Express.js",
  "HTML5",
  "CSS3",
  "JavaScript (ES6+)",
  "Front-end Frameworks and Libraries like React",
  "Bootstrap",
  "jQuery",
  "Laravel",
  "Symfony)",
  "ASP.NET Core",
  "Java (Spring Boot)",
  "Relational Databases",
  "Oracle DB)",
  "NoSQL Databases",
  "Firebase)",
  "Graph Databases (Neo4j)",
  "Time Series Databases (InfluxDB)",
  "Hive",
  "Pig",
  "Kafka",
  "Jenkins",
  "Ansible",
  "Puppet",
  "Chef",
  "Terraform",
  "AWS CloudFormation",
  "Linux Distributions Ubuntu",
  "CentOS",
  "Fedora",
  "macOS",
  "Android OS",
  "Python",
  "C#",
  "Unit Testing",
  "JUnit",
  "NUnit",
  "pytest",
  "Functional Testing",
  "Performance Testing",
  "JMeter",
  "LoadRunner",
  "Security Testing",
  "Test Automation Tools Selenium",
  "Appium",
  "Agile methodologies Scrum",
  "Kanban",
  "PMBOK Guide",
  "Project Planning and Scheduling",
  "Natural Language Processing (NLP)",
  "VMware vSphere",
  "Hyper-V",
  "IoT Platforms (AWS IoT)",
  "Azure IoT Hub",
  "Google Cloud IoT",
  "IoT Protocols MQTT",
  "CoAP",
  "HTTP",
  "IoT Devices and Sensors",
  "Augmented Reality (AR)",
  "Virtual Reality (VR)",
  "Mixed Reality (MR)",
];
